services:
  postgres:
    image: postgres:16
    container_name: feast-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: feast
      POSTGRES_PASSWORD: feast
      POSTGRES_DB: feast_registry
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
